name: runtests
on: [push]
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "^1.8.0"
      - run: julia --project -e 'import Pkg; Pkg.add(url="https://github.com/mattwigway/OSRM.jl"); Pkg.instantiate(); Pkg.test()'